name: Build all slurm containers

on:
  workflow_dispatch:
    
jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - 20.11.9
          - 21.08.8-2
          - 22.05.5

    env:
      tag:          ghcr.io/eth-cscs/slurm-container-${{ matrix.version }}:latest
      context:      slurm-${{ matrix.version }}
      extra_flags:  --build-arg SLURM_ROOT=/usr --build-arg SLURM_CONFDIR=/etc/slurm

    steps:
    - uses: actions/checkout@v3
    - name: Login
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build the Docker image
      run: docker build ${{ env.context }} --tag ${{ env.tag }} ${{ env.extra_flags }}
    - name: Push Docker Image
      run: docker push ${{ env.tag }}
